name: Release Assets

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}" -D officialBuild
      - name: Package Linux Build
        run: |
          cd export/release/linux/bin
          zip -r ${{ github.workspace }}/FNF-ZSEngine-linux.zip .
          cd ${{ github.workspace }}
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: FNF-ZSEngine-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
          haxelib-version: 'latest'
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          echo "HAXELIB_PATH=$HOME/haxe/lib" >> $env:GITHUB_ENV
          .\"setup/windows.bat"
        shell: cmd
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> %USERPROFILE%/settings.cocoa
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"  -D officialBuild
      - name: Package Windows Build
        run: |
          cd export/release/windows/bin
          Compress-Archive -Path * -DestinationPath ..\..\..\..\FNF-ZSEngine-windows.zip -Force
        shell: powershell
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: FNF-ZSEngine-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  buildMac:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"  -D officialBuild
      - name: Package Mac Build
        run: |
          cd export/release/macos/bin
          zip -r ${{ github.workspace }}/FNF-ZSEngine-mac.zip .
          cd ${{ github.workspace }}
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: FNF-ZSEngine-mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}